// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyVersionAttribute("1.8.0")>]
[<assembly: AssemblyFileVersionAttribute("1.8.0")>]
[<assembly: AssemblyMetadataAttribute("githash","276d18")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyVersion = "1.8.0"
    let [<Literal>] AssemblyFileVersion = "1.8.0"
    let [<Literal>] AssemblyMetadata_githash = "276d18"
