// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyVersionAttribute("1.7.0")>]
[<assembly: AssemblyFileVersionAttribute("1.7.0")>]
[<assembly: AssemblyMetadataAttribute("githash","e79c0a")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyVersion = "1.7.0"
    let [<Literal>] AssemblyFileVersion = "1.7.0"
    let [<Literal>] AssemblyMetadata_githash = "e79c0a"
