// <auto-generated/>
using System.Reflection;

[assembly: AssemblyVersionAttribute("1.7.0")]
[assembly: AssemblyFileVersionAttribute("1.7.0")]
[assembly: AssemblyMetadataAttribute("githash","c68a9a")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyVersion = "1.7.0";
        internal const System.String AssemblyFileVersion = "1.7.0";
        internal const System.String AssemblyMetadata_githash = "c68a9a";
    }
}
